### PR TITLE
Pin cloudscale terraform provider to 4.0

### PR DESCRIPTION
**Pull request by haasad**
Use 4.0 provider, pin to < 5 to prevent breaking changes like with 4.0

https://github.com/cloudscale-ch/terraform-provider-cloudscale/blob/master/CHANGELOG.md#400

## Checklist

- [x] Keep pull requests small so they can be easily reviewed.
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

### CODE REVIEW

**Review by simu — APPROVED** [review]

**Comment by simu** [comment]
Alternatively, we could use a fixed version (4.0.0 for now), and let Renovate create PRs for new versions?

**Review by glrf — APPROVED** [review]
LGTM. But we need to remember to update our install guide (still uses `CLOUDSCALE_TOKEN`). Not sure if we use it anywhere else.

**Comment by haasad** [comment]
> Alternatively, we could use a fixed version (4.0.0 for now), and let Renovate create PRs for new versions?

Fine by me, what do you prefer?

**Comment by simu** [comment]
> > Alternatively, we could use a fixed version (4.0.0 for now), and let Renovate create PRs for new versions?
> 
> Fine by me, what do you prefer?

I'd prefer to remove the range for the cloudscale provider and let Renovate create PRs for new versions.

**Comment by simu** [comment]
Probably makes sense to update the PR title to reflect the latest changes

**Pull request merged**
